### ISSUE TITLE
Unable to open the file in the child

### ISSUE THREAD

**Issue by mutable-dan** [jerome-pouiller/reredirect#18]
hello
I've been using reredirect with no issues on arm but i recently saw this error 

**Unable to open the file in the child**

i traced the code but was not sure of the cause.  does anyone have any thoughts?

thanks

**Comment by jerome-pouiller** [comment]
I think that `open()` returned an error. Unfortunately, `reredirect` does not retrieve `errno`. So we can't get the details.

You have to guess. Common errors are `permission denied` or `no such file or directory` (in case an intermediate directory in the path does not exist).

**Comment by mutable-dan** [comment]
running as root and not giving a path (just a filename), so not sure, but thank you
