### ISSUE TITLE
"Unable to attach to pid: Input/output error"

### ISSUE THREAD

**Issue by bradynapier** [jerome-pouiller/reredirect#5]
What would cause this to occur?  It happens on almost every single process on one linux box and not on the other (running same firmwares and programs).  Hoping it's a simple fix!

**Comment by anthony-o** [comment]
I've got this same error when running `reredirect` from inside a Docker container. Perhaps that's the same thing that is happening to you?

**Comment by anthony-o** [comment]
Following https://github.com/docker/docker/issues/7276 , I launched my container with `--cap-add SYS_PTRACE` and made `reredirect` work correctly.

**Comment by jerome-pouiller** [comment]
@anthony-o Thank you for resolving this bug. I will try to improve error message.

**Comment by jerome-pouiller** [comment]
Closing this bug since it does not provide enough information to be solved.
