### ISSUE TITLE
redirect can not catch the output of nodejs process.

### ISSUE THREAD

**Issue by guoxiangyang** [jerome-pouiller/reredirect#6]
redirect can not catch the output of nodejs process.

**Comment by jerome-pouiller** [comment]
Dear @guoxiangyang,

Can you provide a test case that reproduce problem?

Thank you.

**Comment by guoxiangyang** [comment]
1. test.js
```
var i = 0;
setInterval(function() {
    console.log(i); i++
}, 1000)
```

2. run it
```
node test.js
```
ps ax | grep "node.js"
Then use redirect to capture the output, nothing happend.

**Comment by jerome-pouiller** [comment]
This test case works correctly here. Does `reredirect` provide any error?
