### ISSUE TITLE
Could consider force stdout to line-buffered after attached?

### ISSUE THREAD

**Issue by vancepym** [jerome-pouiller/reredirect#8]
If target process's stdout was redirected, it is full buffered(size=4096) in general.
`# reredirect -m /tmp/log PID`
`# tail -f /tmp/log`
if `stdout` is set to line buffered, then the `tail` output will be immediate.

Maybe should do the following operation automatically after attached:
```
setvbuf(stdout, NULL, _IOLBF, 0);
```

see also: 
* http://www.pixelbeat.org/programming/stdio_buffering/
* https://linux.die.net/man/3/setvbuf

**Comment by jerome-pouiller** [comment]
Unfortunately, calling `setvbuf` is not a trivial task. It is necessary to get resolve symbols `setvbuf` and `stdout`. In add, this feature is specific to libc and I would like to keep `reredirect` generic.

For your specific problem, I think you could resolve it with

    gdb --pidd=<PID>  --batch-silent -ex "p setvbuf(stdout, NULL, _IOLBF, 0)"
