### ISSUE TITLE
Cross-compiling reredirect for ARM

### ISSUE THREAD

**Issue by rsmlgen** [jerome-pouiller/reredirect#9]
There is no configure file, so how can I cross-compile reredirect for ARM?

**Comment by jerome-pouiller** [comment]
Try:

     make CC={YOUR_CROSSCOMPILER}-gcc

**Comment by rsmlgen** [comment]
Thanks, I've managed to cross-compile and run reredirect on my ARM structure, but there is a small issue that I can't understand. When I run reredirect sometimes it returns nothing and locks down the shell, and after stopping reredirect and running again it works. I am trying to automate output redirection and this problem bugs me.

**Comment by jerome-pouiller** [comment]
@rsmlgen Can you open a new issue please.
